name: Create index.json on new release

env:
  DOTNET_VERSION: 7.x
  
on:
  workflow_run:
    workflows: [Create a release]
    types:
      - completed
  workflow_dispatch:
    inputs:
      isDraft:
        type: boolean
        default: true
        description: 'Create a draft'

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  main-job:
    # ⚠️ Ensure the workflow runs only for Astroneer mods repositories.
    if: ${{ github.event.workflow_run.conclusion == 'success' && endsWith(github.repository_owner, '-Astroneer-mods') }}

    runs-on: windows-latest
    
    steps:
    - name: Init
      run: |
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8

    - name: Show release info
      run: |
        Write-Output "Release tag: ${{ github.event.release.tag_name }}"
        Write-Output "Release name: ${{ github.event.release.name }}"
        Write-Output "Ref name: ${{ github.ref_name }}"
        Write-Output "Is draft: ${{ github.event.release.draft }}"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        .\ci\set-vars.ps1 -github_ref_name '${{ github.ref_name }}' -github_repository $env:GITHUB_REPOSITORY

    - name: Run the game-specific script (if exists)
      run: |
        .\ci\game-specific.ps1

    - name: Create index.json
      run: |
        .\games\astroneer\ci\create-index_json.ps1

    - name: Commit index.json
      run: |
        .\games\astroneer\ci\commit-index_json.ps1
